// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb.proto

It has these top-level messages:
	KV
	KVList
	ManifestChange
	ManifestChangeSet
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ManifestChange_Operation int32

const (
	ManifestChange_CREATE ManifestChange_Operation = 0
	ManifestChange_DELETE ManifestChange_Operation = 1
)

var ManifestChange_Operation_name = map[int32]string{
	0: "CREATE",
	1: "DELETE",
}
var ManifestChange_Operation_value = map[string]int32{
	"CREATE": 0,
	"DELETE": 1,
}

func (x ManifestChange_Operation) String() string {
	return proto.EnumName(ManifestChange_Operation_name, int32(x))
}
func (ManifestChange_Operation) EnumDescriptor() ([]byte, []int) { return fileDescriptorPb, []int{2, 0} }

type KV struct {
	Key       []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value     []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	UserMeta  []byte `protobuf:"bytes,3,opt,name=user_meta,json=userMeta,proto3" json:"user_meta,omitempty"`
	Version   uint64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	ExpiresAt uint64 `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Meta      []byte `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (m *KV) Reset()                    { *m = KV{} }
func (m *KV) String() string            { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()               {}
func (*KV) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{0} }

func (m *KV) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KV) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KV) GetUserMeta() []byte {
	if m != nil {
		return m.UserMeta
	}
	return nil
}

func (m *KV) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *KV) GetExpiresAt() uint64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *KV) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

type KVList struct {
	Kv []*KV `protobuf:"bytes,1,rep,name=kv" json:"kv,omitempty"`
}

func (m *KVList) Reset()                    { *m = KVList{} }
func (m *KVList) String() string            { return proto.CompactTextString(m) }
func (*KVList) ProtoMessage()               {}
func (*KVList) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{1} }

func (m *KVList) GetKv() []*KV {
	if m != nil {
		return m.Kv
	}
	return nil
}

type ManifestChange struct {
	Id       uint64                   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Op       ManifestChange_Operation `protobuf:"varint,2,opt,name=Op,proto3,enum=pb.ManifestChange_Operation" json:"Op,omitempty"`
	Level    uint32                   `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`
	Checksum []byte                   `protobuf:"bytes,4,opt,name=Checksum,proto3" json:"Checksum,omitempty"`
}

func (m *ManifestChange) Reset()                    { *m = ManifestChange{} }
func (m *ManifestChange) String() string            { return proto.CompactTextString(m) }
func (*ManifestChange) ProtoMessage()               {}
func (*ManifestChange) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{2} }

func (m *ManifestChange) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ManifestChange) GetOp() ManifestChange_Operation {
	if m != nil {
		return m.Op
	}
	return ManifestChange_CREATE
}

func (m *ManifestChange) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *ManifestChange) GetChecksum() []byte {
	if m != nil {
		return m.Checksum
	}
	return nil
}

// A set of changes that are applied atomically.
type ManifestChangeSet struct {
	Changes []*ManifestChange `protobuf:"bytes,1,rep,name=changes" json:"changes,omitempty"`
}

func (m *ManifestChangeSet) Reset()                    { *m = ManifestChangeSet{} }
func (m *ManifestChangeSet) String() string            { return proto.CompactTextString(m) }
func (*ManifestChangeSet) ProtoMessage()               {}
func (*ManifestChangeSet) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{3} }

func (m *ManifestChangeSet) GetChanges() []*ManifestChange {
	if m != nil {
		return m.Changes
	}
	return nil
}

func init() {
	proto.RegisterType((*KV)(nil), "pb.KV")
	proto.RegisterType((*KVList)(nil), "pb.KVList")
	proto.RegisterType((*ManifestChange)(nil), "pb.ManifestChange")
	proto.RegisterType((*ManifestChangeSet)(nil), "pb.ManifestChangeSet")
	proto.RegisterEnum("pb.ManifestChange_Operation", ManifestChange_Operation_name, ManifestChange_Operation_value)
}

func init() { proto.RegisterFile("pb.proto", fileDescriptorPb) }

var fileDescriptorPb = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xdd, 0x6a, 0xea, 0x40,
	0x14, 0x85, 0x4f, 0xc6, 0x18, 0x75, 0x1f, 0x8f, 0x78, 0x36, 0xa5, 0x0c, 0xfd, 0x81, 0x90, 0xde,
	0x78, 0x21, 0xb9, 0xb0, 0x4f, 0x20, 0x36, 0x17, 0xa2, 0x22, 0x4c, 0xc5, 0x5b, 0x99, 0xe8, 0x6e,
	0x0d, 0xd1, 0x64, 0xc8, 0x8c, 0xa1, 0x7d, 0x91, 0xbe, 0x41, 0xdf, 0xb3, 0x64, 0xfc, 0x01, 0xe9,
	0xdd, 0x5a, 0x6b, 0xef, 0x59, 0x33, 0x1f, 0x03, 0x4d, 0x15, 0x87, 0xaa, 0xc8, 0x4d, 0x8e, 0x4c,
	0xc5, 0xc1, 0x97, 0x03, 0x6c, 0xb2, 0xc4, 0x2e, 0xd4, 0x52, 0xfa, 0xe4, 0x8e, 0xef, 0xf4, 0xda,
	0xa2, 0x92, 0x78, 0x03, 0xf5, 0x52, 0xee, 0x0e, 0xc4, 0x99, 0xcd, 0x8e, 0x06, 0xef, 0xa1, 0x75,
	0xd0, 0x54, 0xac, 0xf6, 0x64, 0x24, 0xaf, 0xd9, 0x49, 0xb3, 0x0a, 0x66, 0x64, 0x24, 0x72, 0x68,
	0x94, 0x54, 0xe8, 0x24, 0xcf, 0xb8, 0xeb, 0x3b, 0x3d, 0x57, 0x9c, 0x2d, 0x3e, 0x02, 0xd0, 0x87,
	0x4a, 0x0a, 0xd2, 0x2b, 0x69, 0x78, 0xdd, 0x0e, 0x5b, 0xa7, 0x64, 0x68, 0x10, 0xc1, 0xb5, 0x85,
	0x9e, 0x2d, 0xb4, 0x3a, 0xf0, 0xc1, 0x9b, 0x2c, 0xa7, 0x89, 0x36, 0x78, 0x0b, 0x2c, 0x2d, 0xb9,
	0xe3, 0xd7, 0x7a, 0x7f, 0x07, 0x5e, 0xa8, 0xe2, 0x70, 0xb2, 0x14, 0x2c, 0x2d, 0x83, 0x6f, 0x07,
	0x3a, 0x33, 0x99, 0x25, 0x6f, 0xa4, 0xcd, 0x68, 0x2b, 0xb3, 0x77, 0xc2, 0x0e, 0xb0, 0xf1, 0xc6,
	0x52, 0xb8, 0x82, 0x8d, 0x37, 0xd8, 0x07, 0x36, 0x57, 0x96, 0xa0, 0x33, 0x78, 0xa8, 0x8e, 0x5e,
	0xef, 0x87, 0x73, 0x45, 0x85, 0x34, 0x49, 0x9e, 0x09, 0x36, 0x57, 0x15, 0xf2, 0x94, 0x4a, 0xda,
	0x59, 0xb0, 0x7f, 0xe2, 0x68, 0xf0, 0x0e, 0x9a, 0xa3, 0x2d, 0xad, 0x53, 0x7d, 0xd8, 0x5b, 0xac,
	0xb6, 0xb8, 0xf8, 0xe0, 0x09, 0x5a, 0x97, 0x0a, 0x04, 0xf0, 0x46, 0x22, 0x1a, 0x2e, 0xa2, 0xee,
	0x9f, 0x4a, 0xbf, 0x44, 0xd3, 0x68, 0x11, 0x75, 0x9d, 0x60, 0x08, 0xff, 0xaf, 0xaf, 0x7d, 0x25,
	0x83, 0x7d, 0x68, 0xac, 0xad, 0xd1, 0x27, 0x32, 0xfc, 0xfd, 0x3c, 0x71, 0x5e, 0x89, 0x3d, 0xfb,
	0x61, 0xcf, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x68, 0x1f, 0x95, 0xa4, 0xbc, 0x01, 0x00, 0x00,
}
